### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Lapan** [cruor99/sadpandareader#39]
App often feels like it's slow to respond when sliding out the menu or switching between menus. In extreme cases it's going as far as crashing (couldn't reproduce that crash though)

**Comment by Lapan** [comment]
The setting menu seems particulary slow

**Comment by cruor99** [comment]
Was the crash when going back from a gallery to the preview? If so I know of it, and I'm trying to fix the particular error. It seems to triggering somewhat deeper than my code, so it could be the multiple on_touch_moves on both the "button" that's there, and the gesture.

The setting menu also seems to duplicate itself each time you go into it, so a simple enough fix.
